### ISSUE TITLE
Can we use Hilt with this architecture

### ISSUE THREAD

**Issue by vyshas** [Morfly/jetpack-compose-arch-sample#3]
Hi, 

We are looking at an architecture very similar to this and one question where had doubts was will we be able to use Hilt properly with this architecture ?

**Comment by AradiPatrik** [comment]
He mentioned in his talk that this architecture is not really compatible with hilt.
As I understood: Hilt uses `@Submcomponent` instead of component dependencies in it's implementation and that means that your implementation modules have to explicitly depend on other implementation and app modules using hilt. And that sort of defeats the purpose of this architecture.

**Comment by Morfly** [comment]
That's correct, the main issue lies in the fact that Hilt uses subcomponents under the hood, which in turn makes `api`-`impl` more challenging.
Thank you @AradiPatrik for the reply!
